### PR TITLE
Geo fixes

### LINKED ISSUE #279: Many non-localized labels
At some point we need to do a big pass and localize all the labels... In various default editor panels there are ones that aren't wrapped in `_( )` :)

### LINKED ISSUE #526: Geo Layout
For choropleth traces

### LINKED ISSUE #531: ensure that trace group names are localized

### LINKED ISSUE #657: Switching from variable to constant should hide colorscale
otherwise the widget goes away but the scale is still there.

### PR DESCRIPTION
**Pull request by dmt0**
- Closes #526
- Closes #279
- Closes #657
- Closes #531
- fix bug: cannot create annotations/shapes/images in non-cartesian traces

geo fixes:
- axes panel - visibility issues and missing widgets (feature parity stuff)
- correct options for fill dropdown
- StyleTracePanel sections missing for atlas maps

### CODE REVIEW

File: src/components/fields/FilterOperation.js [hunk 1]
```diff
@@ -132,10 +134,40 @@ UnconnectedFilterOperation.propTypes = {
...
+UnconnectedFilterOperation.contextTypes = {
+  localize: PropTypes.func,
+};
 
 class UnconnectedFilterValue extends Component {
   constructor(props, context) {
     super(props, context);
+    const {localize: _} = context;
+
+    // Replicated so that strings can be statically analyzed for localization
```
Comment (nicolaskruchten) [inline src/components/fields/FilterOperation.js]: why is replication needed?

File: src/default_panels/GraphSubplotsPanel.js [hunk 2]
```diff
@@ -114,6 +114,33 @@ const GraphSubplotsPanel = (props, {localize: _}) => (
...
+        attr="resolution"
+        options={[
+          {label: _('1:110,000,000'), value: 110},
+          {label: _('1:50,000,000'), value: 50},
+        ]}
+      />
+      <Numeric label={_('Scale')} attr="projection.scale" min={0} />
+    </PlotlySection>
+
+    <PlotlySection name={_('Map Rotation')}>
```
Comment (nicolaskruchten) [inline src/default_panels/GraphSubplotsPanel.js]: I would key frame and rotation at the bottom, personally. not sure if anyone knows enough math to actually edit the rotation numbers tho

File: src/components/fields/FilterOperation.js (hunk 1 above)
Comment (dmt0) [reply src/components/fields/FilterOperation.js]: My guess was that there's a script that does static analysis of the code and adds strings to the translation files, so this thing needs to live inside a component. Tried putting it in one and accessing from another - like UnconnectedFilterValue.operation - no luck. What's the way?

Comment (nicolaskruchten) [reply src/components/fields/FilterOperation.js]: @VeraZab ?

**Comment by nicolaskruchten** [comment]
not sure the error messages really need to be localized, but I appreciate the thoroughness :)

**Comment by dmt0** [comment]
no idea what percy is doing, I see all panels just fine locally

File: src/default_panels/GraphSubplotsPanel.js (hunk 2 above)
Comment (dmt0) [reply src/default_panels/GraphSubplotsPanel.js]: it's there in cloud ya know, and I thought to put all relevant things together, everything below has to do with map contents...

Comment (nicolaskruchten) [reply src/default_panels/GraphSubplotsPanel.js]: yeah let's make map contents the top stuff please, and leave the weird stuff at the bottom

File: src/components/fields/FilterOperation.js (hunk 1 above)
Comment (VeraZab) [reply src/components/fields/FilterOperation.js]: you could make it a function? and pass in localize as a prop?

File: src/default_panels/GraphSubplotsPanel.js [hunk 3]
```diff
@@ -114,6 +114,33 @@ const GraphSubplotsPanel = (props, {localize: _}) => (
           {label: _('Sinusoidal'), value: 'sinusoidal'},
         ]}
       />
+      <Radio
+        label={_('Resolution')}
+        attr="resolution"
+        options={[
+          {label: _('1:110,000,000'), value: 110},
+          {label: _('1:50,000,000'), value: 50},
```
Comment (VeraZab) [inline src/default_panels/GraphSubplotsPanel.js]: that label title is a little weird no?

Comment (dmt0) [reply src/default_panels/GraphSubplotsPanel.js]: that's what is in cloud - most importantly it will be translated to all languages :)

File: src/default_panels/GraphSubplotsPanel.js (hunk 2 above)
Comment (dmt0) [reply src/default_panels/GraphSubplotsPanel.js]: done

**Comment by VeraZab** [comment]
💃 on the code

File: src/default_panels/GraphSubplotsPanel.js (hunk 2 above)
Comment (nicolaskruchten) [reply src/default_panels/GraphSubplotsPanel.js]: OK but the region and projection should stay at the top :) the Frame and Rotation and Scale and Resolution should be at the bottom :)

File: src/default_panels/StyleAxesPanel.js [hunk 4]
```diff
@@ -150,6 +152,8 @@ class StyleAxesPanel extends Component {
             />
             <Numeric label={_('Thickness')} attr="gridwidth" units="px" />
             <ColorPicker label={_('Color')} attr="gridcolor" />
+            <Numeric label={_('Reference')} attr="tick0" units="deg" />
```
[the remark this answers is not in the document]
Comment (nicolaskruchten) [reply src/default_panels/StyleAxesPanel.js]: do a search for `dtick` and you'll see

[the remark this answers is not in the document]
Comment (nicolaskruchten) [reply src/default_panels/StyleAxesPanel.js]: see also https://github.com/plotly/react-chart-editor/issues/535 which is the same-ish issue: attrs with the same name in different trace-type/axes that should have different labels/treatment
